apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-docker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-docker
  template:
    metadata:
      labels:
        app: go-docker
    spec:
      containers:
        - name: go-docker
          image: harbor.test.h.cn/rke-lab/go-docker
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: go-docker
spec:
  type: NodePort
  selector:
    app: go-docker
  ports:
    - port: 80
      targetPort: 8080
